project_id = "lnhuwbfyygbffpyelzfb"

[functions.send-ticket-notification]
verify_jwt = false

[functions.github-webhook-deploy]
verify_jwt = false

[functions.high-value-alert]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false
